### ISSUE TITLE
Is this check necessary if we restrict them to select the past dates in the JavaScript? 

### ISSUE THREAD

**Issue by cpong1** [MrTaooo/SPM_KuihScrum#1]
![Screenshot 2023-10-05 203100](https://github.com/SPM-Kuih-Git/SPM_KuihScrum/assets/40486171/1a079b07-f6e8-47dd-bfe0-9ffb133815c1)

**Comment by MrTaooo** [comment]
No sir, you can delete it (because backend already checked for this)
